### ISSUE TITLE
Support arbitrary prefixes/patterns of inputs

### ISSUE THREAD

**Issue by nazarewk** [katrinafyi/nix-patcher#1] opened 2024-11-12 09:15 UTC
I have found out the hard way that `nix-patcher` considers all inputs it finds an instance of `nixpkgs`.

It would be useful to tell it a prefix/pattern to handle in a concrete run, eg: `--input-prefix=nixpkgs-` or `--input-glob=nixpkgs-*`.

**Comment by katrinafyi** [comment] 2024-11-12 09:44
Hello, thanks for your feedback!

By design, it should support patching of any inputs. I don't believe it requires or assumes any of them are nixpkgs.

However, maybe I've made a mistake somewhere. What kinds of problems does this cause? Do you have a flake.nix which I can have a look at?

**Comment by nazarewk** [comment] 2024-11-12 10:10
It patches any input, but doesn't concern itself with:
- which upstream goes to which patched input
- which patch goes to which upstream/patched input

I might be wrong, but it probably tries to use the same upstream and same set of patches on all inputs.
I am pretty sure it would fail for anything having more than just `nixpkgs` in it's inputs.

I tried to use [this flake's inputs](https://github.com/nazarewk-iac/nix-configs/blob/main/nixpkgs-patcher/flake.nix) inside [this flake](https://github.com/nazarewk-iac/nix-configs/blob/b08c00272a12247c3d633d3f7c6862efe5dc1cac/flake.nix#L2-L43), but it failed miserably and had to put it into separate subfolder to make it work at all.

**Comment by katrinafyi** [comment] 2024-11-12 10:23
That seems serious, I'll look into it.

**Comment by katrinafyi** [comment] 2024-11-12 12:45
I've found a crash with additional inputs (i.e. those which are not patches, forks, or upstreams). I have not found any instances of upstream/patches being used across inputs. When you say "to make it work at all", was it simply crashing? Did you see any behaviour that suggested it was mixing patches across inputs?

In any case, I'm working on a fix at https://github.com/katrinafyi/nix-patcher/pull/2 and I would appreciate your help testing. 

The flake I tested this fix with is [flake.nix.txt](https://github.com/user-attachments/files/17716688/flake.nix.txt). This includes a few cases but it is obviously less than your full flake. Notably, it doesn't use follows, but I don't think that should matter here.

**Comment by nazarewk** [comment] 2024-11-12 13:07
as noted, the crash seems to have been the issue I had.

Also looks like you are already doing the matching by repository name on GitHub it would be worth noting this in README as sometimes the forks do not match the original's repository name.

**Comment by katrinafyi** [comment] 2024-11-12 13:29
Do you mean something like
```nix
  # no patches, different repo names
  inputs.nixpkgs6.url = "github:nazarewk/nixpkgs/nixos-unstable";
  inputs.nixpkgs6-upstream.url = "github:katrinafyi/pac-nix";
```
causes problems for you? If so, this would be a bug... All matching should be done only by the flake input name.

**Comment by nazarewk** [comment] 2024-11-12 15:43
I mean more like:
```nix
  inputs.nixpkgs.url = "github:nazarewk/my-nixpkgs-fork/nixos-unstable";
  inputs.nixpkgs-upstream.url = "github:nixos/nixpkgs/nixos-unstable";
```

My bad, I thought then name in https://github.com/katrinafyi/nix-patcher/blob/4f17dec1512e2517ff4118ea3b17842b0b1aec94/patcher.py#L119 was repository's name, but it seems to really match the repo by cutting out patch/upstream suffixes so it already works properly for whatever I wouldn't put there.

**Comment by katrinafyi** [comment] 2024-11-12 23:01
I see. In that case, you can close this issue if you think the feature is no longer necessary.

**Closed as completed** 2024-11-13 06:57 UTC
